INSERT INTO product (title, store, brand, category, price, item_description) VALUES
('Spray and Wipe', 'Coles', 'Ajax', 'Cleaning' ,15.43, 'Kills 99.9% of germs'),
('Spray and Wipe', 'Woolworths', 'Ajax', 'Cleaning' ,16.00, 'Kills 99.9% of germs'),
('Spray and Wipe', 'Aldi', 'Ajax', 'Cleaning' ,14.00, 'Kills 99.9% of germs'),
('Sliced Cheese', 'Coles', 'The Cheese Company', 'Dairy' ,16.56, 'New Zealand sourced cheese, made with love'),
('Sliced Cheese', 'Woolworths', 'The Cheese Company', 'Dairy' ,16.56,' New Zealand sourced cheese, made with love'),
('Chips', 'Woolworths', 'Smith''s', 'Snacks' ,1.94,'Original Smith chips that make you smile'),
('Toilet Paper', 'Woolworths', 'Kleenex', 'Cleaning' ,1.94,'Clean after every go!'),
('Toilet Paper', 'Coles', 'Kleenex', 'Cleaning' ,1.94,'Clean after every go!'),
('Toilet Paper', 'Aldi', 'Kleenex', 'Cleaning' ,1.94,'Clean after every go!'),
('Milk', 'Coles', 'A2 Milk', 'Dairy' ,17.30, 'Milk from dairy cows'),
('Milk', 'Woolworths', 'A2 Milk', 'Dairy' ,4.30, 'Milk from dairy cows'),
('Milk', 'Aldi', 'A2 Milk', 'Dairy' ,12.45, 'Milk from dairy cows'),
('Chicken Breast', 'Coles', 'Coles', 'Meat' ,15.40, 'Prices are per kg. RSPCA approved'),
('Chicken Breast', 'Woolworths', 'Woolworths', 'Meat' ,17.00, 'Prices are per kg. RSPCA approved'),
('Chicken Breast', 'Aldi', 'Aldi', 'Meat' ,10.00, 'Prices are per kg. RSPCA approved'),
('Fresh Tomato Each', 'Coles', 'Coles', 'Fresh produce' ,0.63, 'Round in shape, with a bright red shiny skin and red pulp and whitish seeds.'),
('Fresh Tomato Each', 'Woolworths', 'Woolworths', 'Fresh produce' ,0.42,' Round in shape, with a bright red shiny skin and red pulp and whitish seeds.'),
('Cavendish Bananas', 'Woolworths', 'Woolworths', 'Fresh produce' ,0.81,'Cavendish is the most popular banana variety in Australia, with firm, starchy flesh and available all year round.'),
('Cavendish Bananas', 'Coles', 'Coles', 'Fresh produce' ,0.88,'Cavendish is the most popular banana variety in Australia, with firm, starchy flesh and available all year round.'),
('Hass avocado', 'Coles', 'Coles', 'Fresh produce' ,1.30, 'Famous for their smooth, buttery flesh Hass avocados are a delightful addition to any meal.'),
('Hass avocado', 'Woolworths', 'Woolworths', 'Fresh produce' ,1.30, 'Famous for their smooth, buttery flesh Hass avocados are a delightful addition to any meal.'),
('Hass avocado', 'Aldi', 'Aldi', 'Fresh produce' ,1.00, 'Famous for their smooth, buttery flesh Hass avocados are a delightful addition to any meal.'),
('Mission Wraps Spinach & Herb', 'Coles', 'Mission', 'Bakery' ,5.00, 'Mission Spinach and Herb Super Soft Wraps are super soft and super versatile!'),
('Mission Wraps Spinach & Herb', 'Woolworths', 'Mission', 'Bakery' ,5.50, 'Mission Spinach and Herb Super Soft Wraps are super soft and super versatile!'),
('Wonder White Bread', 'Coles', 'Wonder White', 'Bakery' ,4.40, 'Make the ultimate sandwich with Wonder High Fibre, Vitamins & Minerals White Sliced Bread Sandwich. Its super soft, full of goodness and tastes great with your favourite fillings or spreads.'),
('Wonder White Bread', 'Woolworths', 'Wonder White', 'Bakery' ,4.40,' Make the ultimate sandwich with Wonder High Fibre, Vitamins & Minerals White Sliced Bread Sandwich. Its super soft, full of goodness and tastes great with your favourite fillings or spreads.');
